[package]
name = "grafana-sync"
version = "0.1.0"
edition = "2021"
description = "Dashboard synchronization tool for grafana"
license = "MIT"
homepage = "https://github.com/wobcom/grafana-sync"
repository = "https://github.com/wobcom/grafana-sync"

[dependencies]
grafana-sync-federation = { path = "./grafana-sync-federation" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.138"
serde_with = { version = "3.12.0", features = ["chrono_0_4"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "net"] }
chrono = { version = "0.4.39", features = ["serde"] }
log = "0.4.22"
env_logger = "0.11.6"
thiserror = "2.0.11"
reqwest = { version = "0.12.12", features = ["json"] }
tracing = "0.1.41"
uuid = { version = "1.13.1", features = ["v4", "fast-rng"] }
futures = "0.3.31"
config = "0.15.11"
clap = "4.5.38"
