[package]
name = "grafana-sync"
version = "0.1.0"
edition = "2021"
description = "Dashboard synchronization tool for grafana"
license = "MIT"
homepage = "https://github.com/wobcom/grafana-sync"
repository = "https://github.com/wobcom/grafana-sync"

[dependencies]
serde_json = "1.0"
tokio = { version = "1.47", features = ["rt", "rt-multi-thread", "macros"] }
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.11"
thiserror = "2.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tracing = "0.1"
aes-gcm = "0.10"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.18", features = ["v4", "fast-rng"] }
futures = "0.3"
