service:
  instanceMaster:
    url: "https://localhost"
    api_token: "meow1234"

  instanceSlaves:
    - url: "https://localhost:4431"
      api_token: "meow1234"
    - url: "https://localhost:4432"
      api_token: "meow1234"
    - url: "https://localhost:4433"
      api_token: "meow1234"

  dashboards:
    - "Folder/Dashboard"
    - "Folder2/Dashboard"
    - "Folder3/Meowboard"