use log::{debug, info};
use serde::Serialize;
use uuid::Uuid;
use crate::api::dashboards::Folder;
use crate::error::GSError;
use crate::instance::GrafanaInstance;

#[derive(Debug, Clone, Serialize)]
struct FolderBody {
    description: String,
    title: String,
    uid: String,
}

impl GrafanaInstance {
    pub async fn get_all_folders(&mut self) -> Result<Vec<Folder>, GSError> {
        let endpoint = format!("{}{}", &self.base_url(), "/api/folders");
        let client = self.client()?;

        let response = client
            .get(endpoint)
            .query(&[("limit", "1000"), ("page", "1")])
            .send()
            .await?
            .error_for_status()?;
        let text = response.text().await?;

        Ok(serde_json::from_str::<Vec<Folder>>(&text)?)
    }

    // returns the folder uid on the instance
    pub async fn ensure_folder(&mut self, title: &str) -> Result<Folder, GSError> {
        debug!("Ensuring folder {} exists on {}...", title, self.base_url());
        let matching_folder = self.get_all_folders()
            .await?
            .into_iter()
            .filter(|f| f.title == title).next();
        if let Some(folder) = matching_folder {
            debug!("Folder {} already exists", title);
            return Ok(folder);
        }

        let endpoint = format!("{}{}", &self.base_url(), "/api/folders");
        let client = self.client()?;

        let folder_body = FolderBody {
            description: "autogenerated by graphsync".to_string(),
            title: title.to_string(),
            // Could sync uid, but these folders might already exist so we're using a random one here
            // since it's not a reliable metric anyway
            uid: Uuid::new_v4().to_string(),
        };

        let response = client
            .post(endpoint)
            .json(&folder_body)
            .send()
            .await?
            .error_for_status()?;
        let text = response.text().await?;

        let folder = serde_json::from_str::<Folder>(&text)?;
        info!("Folder {} has been created", folder.title);

        Ok(folder)
    }
}