[package]
name = "grafana-sync-federation"
version = "0.1.0"
edition = "2024"
authors = [ "willow" ]
description = "Federation library, originally made for grafana dashboard synchronization"
license = "MIT"
homepage = "https://github.com/wobcom/grafana-sync"
repository = "https://github.com/wobcom/grafana-sync"

[dependencies]
tokio = { version = "1.45.0", features = ["net", "macros", "time", "rt", "rt-multi-thread", "sync"] }
tokio-util = { version = "0.7.15", features = ["codec"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-big-array = "0.5.1"
bincode = { version = "2.0.1", features = ["serde"] }
async-bincode = "0.8.0"
rand = "0.9.1"
thiserror = "2.0.12"
log = "0.4.27"
futures = "0.3.31"
chacha20poly1305 = "0.10.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets", "zeroize"] }
ed25519-dalek = { version = "2.1.1", features = ["zeroize", "pem", "rand_core"] }
memsec = "0.7.0"
zeroize = { version = "1.8.1", features = ["serde"] }
hkdf = "0.12.4"
sha2 = "0.10.9"
dashmap = "6.1.0"
