name: GraphSync CI & Docs

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --all

  rustdoc:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build Docs
        run: cargo doc --no-deps --locked

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-docs
          path: target/doc

  pages:
    runs-on: ubuntu-latest
    needs: rustdoc               # only wait on docs to finish
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: rust-docs
          path: target/doc

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
